import SideBar from '@/components/SideBar'
import './globals.css'
import { Inter } from 'next/font/google'
import TopBar from '@/components/TopBar'
<<<<<<< HEAD
import { hamburgerProvider } from '@/context/hamburgerContext'
=======
import { BurgerProvider } from '@/context/burgerContext';
>>>>>>> desktop_v_2

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Info-Vault',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
//   const [isOpen,setIsOpen] = useState(false)

//   const handleBurger = () =>{
//     setIsOpen(!isOpen);
//     console.log(isOpen)
// }
  return (
    <html lang="en">
      <body className={inter.className}>
<<<<<<< HEAD
        <hamburgerProvider>
=======
        <BurgerProvider>
>>>>>>> desktop_v_2
        <main className='flex  min-h-screen basis-full max-w-[1440px] mx-auto relative'>
          <SideBar/>
        <section className='flex flex-col w-full'>
        <TopBar/>
        <div className='bg-[#F4F4F4] h-screen md:p-4 lg:p-10 overflow-y-auto'>{children}</div>
        </section>

        </main>
<<<<<<< HEAD
        </hamburgerProvider>
=======
        </BurgerProvider>
>>>>>>> desktop_v_2

        </body>
    </html>
  )
}
