import SideBar from '@/components/SideBar'
import './globals.css'
import { Inter } from 'next/font/google'
import TopBar from '@/components/TopBar'
import { BurgerProvider } from '@/context/burgerContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
//   const [isOpen,setIsOpen] = useState(false)

//   const handleBurger = () =>{
//     setIsOpen(!isOpen);
//     console.log(isOpen)
// }
  return (
    <html lang="en">
      <body className={inter.className}>
        <BurgerProvider>
        <main className='flex  min-h-screen basis-full max-w-[1440px] mx-auto relative'>
          <SideBar/>
        <section className='flex flex-col w-full'>
        <TopBar/>
        <div className='bg-[#F4F4F4] h-screen md:p-4 lg:p-10 overflow-y-auto'>{children}</div>
        </section>

        </main>
        </BurgerProvider>

        </body>
    </html>
  )
}
